### ISSUE TITLE
Issue running MGMTpredict on EPICv2 data

### ISSUE THREAD

**Issue by cewim** [badozor/mgmtstp27#2]
Thank you for your contribution and for making this algorithm freely available. I'm attempting to predict MGMT methylation status on some DNA methylation data generated using the Illumina EPIC chip v 2.0.

When I try to run the function on my data frame of M-values, I get an error that one of the cg probes is missing. I took at closer look at the data frame, and it appears that probe names are duplicated (same probe names but different locations on the array - see below), differentiated by suffixes, e.g., "_TC11." 

![image](https://github.com/badozor/mgmtstp27/assets/128617658/98871703-c972-41a6-920c-7e43e1163240)

I thought this could be the issue, so I removed these suffixes, averaged the values, and tried to re-run MGMTpredict. I'm still getting the same error: "the probe 'cg12981137' is missing!"

Have you successfully run MGMTpredict on EPICv2 data? Do you have suggestions for how to handle this issue?

Thank you very much!

**Comment by badozor** [comment]
Hi,
the use of the EPCv2 is possible in the new version of the R package (version 0.8). Now, the function MGMTpredict uses the two probes "cg12434587_BC11" and "cg12981137_TC11" (which will be renamed as "cg12434587" and "cg12981137"). 
i have add documentation to explain the selection of these probes

thx for your feedback

best,

pierre
